services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      target: production
    environment:
      - BACKEND_HOST=backend
    ports:
      - 80:80
    networks:
      - spring-react
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=files
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}:${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    networks:
      - spring-postgres
      - spring-react
  db:
    container_name: postgres-db
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=files
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}:${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
volumes:
  db-data:
networks:
  spring-postgres:
  spring-react: