#FROM eclipse-temurin:latest
FROM bellsoft/liberica-openjdk-alpine-musl:latest

ARG version='0.0.1-SNAPSHOT'
ARG project=backend

COPY /build/libs/${project}-${version}.jar app.jar

RUN apk update \
 && apk add fontconfig \
 && apk add ttf-dejavu
RUN ln -s /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so && \
    ln -s /lib/libuuid.so.1 /usr/lib/libuuid.so.1 && \
    ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1
ENV LD_LIBRARY_PATH /usr/lib

ENTRYPOINT java -jar /app.jar